- name: Create instance(s)
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    service_account_email: 500502311781-compute@developer.gserviceaccount.com
    credentials_file: /Users/tsimson/ts-tech-project-dev-9847d8e09fd8.json
    project_id: ts-tech-project-dev
    machine_type: g1-small 
    image: centos-7
  tasks:

   - name: Launch Web Host
     gce:
         network: ts-tech-vpc-1
         subnetwork: ts-tech-vpc-1
         zone: us-east1-b
         instance_names: ts-web-host-1
         machine_type: "{{ machine_type }}"
         image: "{{ image }}"
         service_account_permissions: storage-full
         service_account_email: "{{ service_account_email }}"
         credentials_file: "{{ credentials_file }}"
         project_id: "{{ project_id }}"
         ip_forward: True
         tags: [ssh, http-server, https-server,subnet]
     register: gce_web_host_1
   - debug: var=gce_web_host_1

   - name: Wait for SSH to come up
     wait_for: host={{ item.public_ip }} port=22 delay=10 timeout=300
     with_items: "{{ gce_web_host_1.instance_data }}"

   - name: Add host to groupname
     add_host: hostname={{ item.name }} ansible_ssh_host={{ item.public_ip }} groupname=ts-web-hosts
     with_items: "{{ gce_web_host_1.instance_data }}"

   - name: Launch DB Host
     gce:
         network: ts-tech-vpc-1
         subnetwork: ts-tech-vpc-1
         zone: us-east1-b
         instance_names: ts-db-host-1
         machine_type: "{{ machine_type }}"
         image: "{{ image }}"
         service_account_email: "{{ service_account_email }}"
         credentials_file: "{{ credentials_file }}"
         project_id: "{{ project_id }}"
         ip_forward: True
         tags: [ssh, subnet]
     register: gce_db_host_1
   - debug: var=gce_db_host_1

   - name: Wait for SSH to come up
     wait_for: host={{ item.public_ip }} port=22 delay=10 timeout=300
     with_items: "{{ gce_db_host_1.instance_data }}"

   - name: Add host to groupname
     add_host: hostname={{ item.name }} ansible_ssh_host={{ item.public_ip }} groupname=ts-db-hosts
     with_items: "{{ gce_db_host_1.instance_data }}"

- name: Manage web-host
  hosts: ts-web-hosts
  connection: ssh
  sudo: True
  roles:
    - role: web_host_role
    - role: wordpress

- name: Manage db-host
  hosts: ts-db-hosts
  connection: ssh
  sudo: True
  roles:
    - role: db_host_role

