---
- name: Copy content files from google storage.
  shell: |
     sudo gsutil cp -r gs://ts-wp-files/html /var/www/

- name: Template wp-config.php to host.
  template:
    src: wp-config.php
    dest: /var/www/html/blog/wp-config.php

- name: Restart services
  shell: |
     sudo systemctl restart nginx
     sudo systemctl restart php-fpm

